# Generated by Django 4.1.7 on 2023-04-21 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)], verbose_name='DNI')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('firstSurname', models.CharField(max_length=70, verbose_name='Primer Apellido')),
                ('secondSurname', models.CharField(max_length=70, verbose_name='Segundo Apellido')),
                ('text', models.TextField(max_length=512, verbose_name='Texto')),
                ('pdf', models.CharField(blank=True, max_length=50, verbose_name='PDF')),
            ],
        ),
    ]
